# Generated by Django 4.1.5 on 2023-01-24 00:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('conteudo', models.CharField(max_length=300)),
                ('carga_horaria', models.IntegerField()),
            ],
        ),
    ]
