# Generated by Django 4.1.5 on 2023-01-24 00:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Disciplina', '0001_initial'),
        ('Aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('np1', models.IntegerField(blank=True, null=True)),
                ('np2', models.IntegerField(blank=True, null=True)),
                ('np3', models.IntegerField(blank=True, null=True)),
                ('npa', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('alunos_ra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aluno.aluno')),
                ('disciplina_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Disciplina.disciplina')),
            ],
        ),
    ]
